### ISSUE TITLE
Checking for odd indices instead of generating them (Recipe 5.5)

### ISSUE THREAD

**Issue by boukeas** [shelleyp/javascriptcookbook#1]
In [Recipe 5.5](https://github.com/shelleyp/javascriptcookbook/blob/master/chap5/recipe5-5.html), this is the code that visits the odd elements of a list:

    for (var i = 0; i < lis.length; i++) {
      if (i % 2 == 0) {
        # do something with lis[i]
      }

But why should we generate all indices and *check* for the odd ones, when we can simply generate the odd ones?

    for (var i = 0; i < lis.length; i+=2) {
      # do something with lis[i]

**Comment by shelleyp** [comment]
Old habits, hard to break.

Your way is better. 

But in the book, the real topic was about modifying elements in an unordered list using a query selector. A preferred way would be to use the :nth-child pseudo class with query selector, which is the best option:

var lis = document.querySelectorAll('li:nth-child(odd)');

At the time the sample was written, not all browsers supported it. All do now. 

But your approach is better using iteration.
